# Numpy 練習

In [ ]:
eps=1e-10 #e^-10をこれで表現
s=0
while abs(s-1)>eps:
    print(s)
    s += 0.1

In [27]:
import numpy as np
#実際には解の公式を数式に落とし込んだって感じ。
def qeq(a,b,c):
    d=np.sqrt(b**2-4*a*c)
    return((-b+d)/(2*a),(-b-d)/(2*a))
qeq(1,5,6)

(-2.0, -3.0)

In [26]:
#解で0に近い値が出てくると有効数字9桁までは誤差が大きな数が並ぶことになるので他の算出法を考える。
#0に近くないほうを算出してからそこから別ルート。
def qeq2(a,b,c):
    d=np.sqrt(b**2-4*a*c)
    minus=(-b-np.sign(b)*d)/(2*a)
    plus=(c/a)/minus
    return(minus,plus)
qeq2(1,5,6)

(-3.0, -2.0)

In [39]:
import numpy as np
def softplus(x):
    return np.log(1+np.exp(x))#np.logとかあるらしい。
softplus(1000)#無限大になってしまうらしいので別の切り口を考える。

inf

In [44]:
def softplus1(x):
    alpha=x+np.log(np.exp(-x)+1)
    return(alpha)
softplus1(1000)

1000.0

In [45]:
#xが正の時にはsoftplus1を負の時にはsoftplusをだせるようにする。
#Infを回避するために必要。

In [54]:
def softplus2(x):
    return(max(0,x)+np.log(1+np.exp(-abs(x))))
softplus2(1000)

1000.0

In [61]:
import numpy as np
np.sqrt(3)
np.pi
np.log(np.e)
np.exp(2)

7.38905609893065

# Numpyの配列(ndarrayというクラスで管理しているらしい)

In [74]:
a=np.array([2,3,4,5,6,7,8])
a[1:3]
b=np.arange(5)#5までの配列を作成する。
c=np.arange(1,4,0.2)
c.dtype

dtype('float64')

# 二次元配列

In [79]:
a=np.array([[2,3,4],[5,6,7]],dtype=np.int64)

In [87]:
a=np.arange(15.).reshape(3,5)
a.ndim
a.size

In [94]:
b=np.arange(4.)
b.shape
b.ndim
b.size

4

In [103]:
c=np.arange(16).reshape(2,-1)
c=c.ravel()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [114]:
#二次元配列に直す、その際に行か列かをセレクトすることができる。
#(行をセレクトすると行方向をキープして二次元配列に変換する。)
d=np.arange(16.)
d[np.newaxis,:]
e=np.arange(12)
e[:,None]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [129]:
a=np.zeros((3,4))
b=np.ones((2,3))
c=np.empty((3,10))
d=np.linspace(0,1,10)

In [138]:
a=np.arange(6).reshape(2,3)
b=np.array([6,7,8,9,10,11,]).reshape(2,3)

In [144]:
#二次元配列を結合する
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [153]:
a=np.arange(10.)
a +=3
a

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [162]:
a=np.arange(19)
a[a>12]
a[(a>=3)&(a<13)]
a[a%3!=0]#配列の後ろでは条件を設定できる。

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17])

In [170]:
a=np.arange(9.).reshape(3,-1)
b=np.arange(4,13.).reshape(3,-1)
a*b #要素ごとの掛け算をする。
np.dot(a,b) #二次元配列だと行列積になる、↑の合算。

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [176]:
a=np.arange(9.).reshape(3,-1)
v=np.arange(1,4)
np.dot(a,v)
u=v.reshape(-1,1)
#np.dot(u,a)
#これは行列積的に正しくない。

In [178]:
a=np.arange(12.).reshape(4,-1)
b=np.arange(3.).reshape(1,-1)
s=np.empty((4,3))
for i in range(4):
    for j in range(3):
        s[i,j]=a[i,j]+b[0,j]

In [185]:
a=np.arange(12.).reshape(4,-1)
c=np.arange(4.).reshape(4,-1)
s=np.empty((4,3))
for i in range(4):
    for j in range(3):
        s[i,j]=a[i,j]*c[i,0] #a*bと同じ、要素ごとに掛ける。（i,j）を考える。


In [186]:
s

array([[ 0.,  0.,  0.],
       [ 3.,  4.,  5.],
       [12., 14., 16.],
       [27., 30., 33.]])

# 疎行列

In [214]:
from scipy import sparse
from scipy.sparse import lil_matrix, csr_matrix

ImportError: cannot import name 'lil_matrix' from 'scipy.sparse' (unknown location)

In [213]:
a=np.zeros((4,5))
a[0,1]=1
a[0,3]=2
a[2,2]=3
a[3,4]=4
a.tocsr()

b=np.zeros((5,4))
b[0,2]=1
b[1,2]=2
b[2,3]=3
b[3,3]=4

AttributeError: 'numpy.ndarray' object has no attribute 'tocsr'

In [210]:
c=np.dot(a,b)
c

array([[0., 0., 2., 8.],
       [0., 0., 0., 0.],
       [0., 0., 0., 9.],
       [0., 0., 0., 0.]])

In [211]:
a1=a.tocsr()
b1=b.tocsr()

AttributeError: 'numpy.ndarray' object has no attribute 'tocsr'